L1-T3 Gagarin + work with time
MisterCat100/Kotlin_Sprint pull request #4
Opened 2023-07-20 15:53 UTC by MisterCat100

2023-07-20 21:15 UTC, ievetrov requested changes
Все ок, но оставил пару комментов для доработки. Пока отклоняю

Чтобы внести изменения нужно будет переключиться в эту ветку, сделать коммит с изменениями и запушить. И отправить ссылку на этот же пулл реквест в бот к соответствующей задаче.

2023-07-20 21:15 UTC, ievetrov commented on src/main/kotlin/Lesson1/task3.kt
> +
Больше одной пустой строки лучше не оставлять

2023-07-20 21:15 UTC, ievetrov commented on src/main/kotlin/Lesson1/task3.kt
> +    var hour = 9
в целом результат есть) но в примере в ТЗ цифры начинаются с 0
вообще нормальная практика, если сервер присылает дату или время строкой.
давай объявим строки и сделаем правильный формат)

2023-07-20 21:23 UTC, MisterCat100 commented on src/main/kotlin/Lesson1/task3.kt
> +    var hour = 9
вы имеете ввиду делать не 9 часов, а 09, как я понял, так еще и строкой?

2023-07-21 18:01 UTC, ievetrov approved these changes
все корректно! теперь эту ветку можно мержить в мастер

2023-07-21 18:03 UTC, merged