L1-T5 Gagarin + time
MisterCat100/Kotlin_Sprint pull request #6
Opened 2023-07-20 17:40 UTC by MisterCat100

надеюсь тут нужно было без readLine()
или как там оно (аналог инпуту на пайтоне)

2023-07-20 21:18 UTC, ievetrov requested changes

2023-07-20 21:18 UTC, ievetrov commented on src/main/kotlin/Lesson1/task5.kt
> +
лишнюю пустую строку лучше тут тоже убрать

2023-07-20 21:18 UTC, ievetrov commented on src/main/kotlin/Lesson1/task5.kt
> +    print(0)
ок, выглядит как рабочий вывод. но так как все пятые задачи "со звездочкой", то предлагаю реализовать более продвинутое решение. попробуй посмотреть как работает String.format()

2023-07-20 21:37 UTC, MisterCat100 commented on src/main/kotlin/Lesson1/task5.kt
> +    print(0)
понял, посмотрю, даже может сегодня переотправлю)

2023-07-21 12:14 UTC, MisterCat100 reviewed
last task

2023-07-21 19:10 UTC, ievetrov approved these changes

2023-07-21 19:24 UTC, merged